---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "REUSE"
permissions: {}
on: [push, pull_request, workflow_dispatch]

jobs:
  reuse:
    name: "REUSE compliance check"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v5
      - name: "REUSE compliance check"
        uses: fsfe/reuse-action@v5
