---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Tags"
permissions: {}
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  update-tag:
    name: "Update the major tag to ${{ github.ref_name }}"
    environment:
      name: "Release"
      url: "https://github.com/marketplace/actions/shellchecker"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "${{ github.run_attempt == '1' && github.ref_type == 'tag' && github.ref_name != '' }}"
    concurrency:
      group: "${{ github.repository_id }}-${{ github.workflow }}-tag-update"
      cancel-in-progress: false
    permissions:
      contents: write

    steps:
      - name: "Update the major tag"
        uses: actions/publish-action@v0.4.0
        with:
          source-tag: "${{ github.ref_name }}"
